# Generated by Django 6.0.7 on 2026-07-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cover', models.CharField(max_length=250)),
                ('stock', models.PositiveIntegerField()),
                ('authors', models.ManyToManyField(to='books.author')),
                ('categories', models.ManyToManyField(to='books.category')),
            ],
        ),
    ]
