# Generated by Django 6.0.7 on 2026-08-05 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='subtotal_price',
            new_name='subtotal',
        ),
    ]
