services:

  db:
    image: postgres:18
    env_file: ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    env_file: ./backend/.env
    environment:
      DB_HOST: db
      DEBUG: "False"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/media:/app/media
      - static_volume:/app/staticfiles
  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - static_volume:/staticfiles
      - ./backend/media:/media
volumes:
  postgres_data:
  static_volume: